# Generated by Django 2.0 on 2018-04-07 23:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 7, 23, 10, 39, 421191)),
        ),
    ]
