# Generated by Django 2.0 on 2018-04-08 21:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_auto_20180407_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 8, 21, 0, 32, 675944, tzinfo=utc)),
        ),
    ]
