# Generated by Django 2.0 on 2018-04-08 22:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_auto_20180408_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 8, 22, 22, 2, 498807, tzinfo=utc)),
        ),
    ]
