# Generated by Django 2.0 on 2018-04-08 22:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0005_auto_20180408_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 8, 22, 22, 36, 944747, tzinfo=utc)),
        ),
    ]
